image: "hseeberger/scala-sbt:graalvm-ce-21.3.0-java11_1.5.6_3.1.0"

stages:
  - test
  - assembly

unit-tests:
  stage: test
  timeout: 3m
  script:
    - sbt test

jvm-jar:
  stage: assembly
  script:
    - sbt assembly
  artifacts:
    name: "akai-jar"
    paths:
      - target/scala-3.1.0/akai.jar
    expire_in: 1 week

graalvm-native-image:
  stage: assembly
  script:
    - gu install native-image
    - sbt graalvm-native-image:packageBin
  artifacts:
    name: "akai-native-image"
    paths:
      - target/graalvm-native-image/akai
    expire_in: 1 week